"""Updated User model with roles and other fields

Revision ID: 62be6f660385
Revises: 164bb8e6a282
Create Date: 2025-05-20 13:51:38.682217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62be6f660385'
down_revision = '164bb8e6a282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
